# -*- coding: utf-8 -*-
"""optimizers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N9xIR8ewNxXWNzlSu9-Wa9aozFbWB4SB
"""

import numpy as np

def sgd(nn, lr, weight_decay=0):
    for layer in nn.layers:
        layer.W -= lr * (layer.grad_W + weight_decay * layer.W)
        layer.b -= lr * layer.grad_b

def momentum(nn, lr, beta=0.9, velocity=None, weight_decay=0):
    if velocity is None:
        velocity = [{'W': np.zeros_like(layer.W), 'b': np.zeros_like(layer.b)} for layer in nn.layers]
    for i, layer in enumerate(nn.layers):
        velocity[i]['W'] = beta * velocity[i]['W'] + layer.grad_W
        velocity[i]['b'] = beta * velocity[i]['b'] + layer.grad_b
        layer.W -= lr * (velocity[i]['W'] + weight_decay * layer.W)
        layer.b -= lr * velocity[i]['b']
    return velocity

def nesterov(nn, lr, beta=0.9, velocity=None, weight_decay=0):
    if velocity is None:
        velocity = [{'W': np.zeros_like(layer.W), 'b': np.zeros_like(layer.b)} for layer in nn.layers]
    for i, layer in enumerate(nn.layers):
        v_prev_W = velocity[i]['W']
        v_prev_b = velocity[i]['b']
        velocity[i]['W'] = beta * velocity[i]['W'] + layer.grad_W
        velocity[i]['b'] = beta * velocity[i]['b'] + layer.grad_b
        layer.W -= lr * ((1 + beta) * velocity[i]['W'] - beta * v_prev_W + weight_decay * layer.W)
        layer.b -= lr * ((1 + beta) * velocity[i]['b'] - beta * v_prev_b)
    return velocity

def rmsprop(nn, lr, beta=0.9, epsilon=1e-8, cache=None, weight_decay=0):
    if cache is None:
        cache = [{'W': np.zeros_like(layer.W), 'b': np.zeros_like(layer.b)} for layer in nn.layers]
    for i, layer in enumerate(nn.layers):
        cache[i]['W'] = beta * cache[i]['W'] + (1 - beta) * (layer.grad_W ** 2)
        cache[i]['b'] = beta * cache[i]['b'] + (1 - beta) * (layer.grad_b ** 2)
        layer.W -= lr * (layer.grad_W / (np.sqrt(cache[i]['W']) + epsilon) + weight_decay * layer.W)
        layer.b -= lr * (layer.grad_b / (np.sqrt(cache[i]['b']) + epsilon))
    return cache

def adam(nn, lr, beta1=0.9, beta2=0.999, epsilon=1e-8, t=1, m=None, v=None, weight_decay=0):
    if m is None:
        m = [{'W': np.zeros_like(layer.W), 'b': np.zeros_like(layer.b)} for layer in nn.layers]
    if v is None:
        v = [{'W': np.zeros_like(layer.W), 'b': np.zeros_like(layer.b)} for layer in nn.layers]
    for i, layer in enumerate(nn.layers):
        m[i]['W'] = beta1 * m[i]['W'] + (1 - beta1) * layer.grad_W
        m[i]['b'] = beta1 * m[i]['b'] + (1 - beta1) * layer.grad_b
        v[i]['W'] = beta2 * v[i]['W'] + (1 - beta2) * (layer.grad_W ** 2)
        v[i]['b'] = beta2 * v[i]['b'] + (1 - beta2) * (layer.grad_b ** 2)
        m_hat_W = m[i]['W'] / (1 - beta1 ** t)
        m_hat_b = m[i]['b'] / (1 - beta1 ** t)
        v_hat_W = v[i]['W'] / (1 - beta2 ** t)
        v_hat_b = v[i]['b'] / (1 - beta2 ** t)
        layer.W -= lr * (m_hat_W / (np.sqrt(v_hat_W) + epsilon) + weight_decay * layer.W)
        layer.b -= lr * (m_hat_b / (np.sqrt(v_hat_b) + epsilon))
    return m, v

def nadam(nn, lr, beta1=0.9, beta2=0.999, epsilon=1e-8, t=1, m=None, v=None, weight_decay=0):
    if m is None:
        m = [{'W': np.zeros_like(layer.W), 'b': np.zeros_like(layer.b)} for layer in nn.layers]
    if v is None:
        v = [{'W': np.zeros_like(layer.W), 'b': np.zeros_like(layer.b)} for layer in nn.layers]
    for i, layer in enumerate(nn.layers):
        m[i]['W'] = beta1 * m[i]['W'] + (1 - beta1) * layer.grad_W
        m[i]['b'] = beta1 * m[i]['b'] + (1 - beta1) * layer.grad_b
        m_hat_W = beta1 * m[i]['W'] + (1 - beta1) * layer.grad_W
        m_hat_b = beta1 * m[i]['b'] + (1 - beta1) * layer.grad_b
        v[i]['W'] = beta2 * v[i]['W'] + (1 - beta2) * (layer.grad_W ** 2)
        v[i]['b'] = beta2 * v[i]['b'] + (1 - beta2) * (layer.grad_b ** 2)
        m_hat_W_corr = m_hat_W / (1 - beta1 ** t)
        m_hat_b_corr = m_hat_b / (1 - beta1 ** t)
        v_hat_W = v[i]['W'] / (1 - beta2 ** t)
        v_hat_b = v[i]['b'] / (1 - beta2 ** t)
        layer.W -= lr * (m_hat_W_corr / (np.sqrt(v_hat_W) + epsilon) + weight_decay * layer.W)
        layer.b -= lr * (m_hat_b_corr / (np.sqrt(v_hat_b) + epsilon))
    return m, v